image: alpine:latest

pages:
    stage: deploy
    script:
        - mkdir public
        - cp -R * ./public
    artifacts:
        paths:
            - public
        exclude:
            - .git/
    only:
        - master