# .gitlab-ci.yml

stages:
  - deploy

# Étape de déploiement
deploy:
  stage: deploy
  script:
    - mkdir -p public  # Crée le dossier de destination final
    # - cp -r public/* public/  # Copie les fichiers du dossier public dans le dossier final public
    - cp -r src/* public/  # Copie les fichiers du dossier src dans public
  artifacts:
    paths:
      - public  # Déclare le dossier public pour le déploiement
  only:
    - master  # Exécute cette étape uniquement sur la branche principale