# .gitlab-ci.yml

stages:
  - deploy

# Étape de déploiement
deploy:
  stage: deploy
  script:
    - mkdir -p temp_public  # Créer un dossier temporaire
    - cp -r src/* temp_public/  # Copier les fichiers de src dans temp_public
    - cp -r public/* temp_public/  # Copier les fichiers de public dans temp_public
    - mv temp_public public  # Remplacer le contenu de public par temp_public
  artifacts:
    paths:
      - public  # Déclare le dossier public pour le déploiement
  only:
    - master  # Exécute cette étape uniquement sur la branche principale